# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Simple CV"
license = "MIT"
licenselink = "https://github.com/hootan09/simple-cv/master/LICENSE"
description = "Theme to build a customizeable printable CV with minor web responsiveness."
homepage = "https://github.com/hootan09/simple-cv"
tags = ["cv", "resume", "minimal", "simple"]
features = ["simple", "cv", "printable"]
min_version = "0.42.0"

[author]
  name = "Inês Almeida, mam niki"
  homepage = "NikiTv.ir"
